sqs:
  local:
    params:
      region: sqs
      endpoint: http://sqs:9324
      apiVersion: "2012-11-05"
    queueName:
      - cvs-edh-test-results-q
  remote:
    params:
      apiVersion: "2012-11-05"
    queueName:
      - cvs-edh-test-results-${BRANCH}-queue

targets:
  test-stations:
    queue: test-stations
    dlQueue: cvs-edh-dispatcher-test-results-${BRANCH}-dlq
    lambdaName: test-stations-${BRANCH}
    targetKey: testStationId
    endpoints:
      POST: test-stations
      PUT: test-stations/{testStationId}
      DELETE: test-stations/{testStationId}

